### PR TITLE
rework states to support automated testing with kitchen-salt and docker

### PR DESCRIPTION
**Pull request by alias454**
Rework states to support automated testing with kitchen-salt and docker:
- add option to enable/disable capture interface
- add library paths when rpm install fails to create file
- install cron package when missing
- add FORMULA file

Formula has been tested with salt >= 2018.3 on:
- Debian 9
- Ubuntu 18.04
- CentOS 7

Other changes:
- add remote logging configuration support for rsyslog

### CODE REVIEW

**Comment by myii** [comment]
@alias454 Thanks for taking this on.  I see that a fair bit of this is taken from the `template-formula` (or similar), which is a good thing.  Could the rest of it be brought into alignment as well?  For example, the structure of `.travis.yml`, the complete `.gitignore` and some of the content and heading symbols used in the `README` (also moving it under the `docs/` directory)?  There are now over 30 formulas that have been converted to this structure and we've got methods to keep them standardised.

**Comment by myii** [comment]
@alias454 And of course: `semantic-release`, which has made a significant difference to all of those formulas.  You're welcome to ping me if you need further information about any of these things.  You can see the whole list of formulas here:

* https://github.com/saltstack-formulas/template-formula/blob/master/docs/CONTRIBUTING.rst#semantic-release-formulas

**Comment by alias454** [comment]
@myii Hi, yes that is my plan to bring this in-line with the template formula as much as possible and eventually integrate the semantic-release changes, along with reworking the osmap, osfamily yaml changes. I wanted to understand it more before I added it to this formula though. Thanks.

**Comment by myii** [comment]
@alias454 That's fine.  In case you want to get an idea of how all of these formulas are kept in sync across the organisation, then this file contains the specifics for each formula's configuration (and the files that are managed):

* [`formulas.yaml`](https://github.com/myii/ssf-formula/blob/ac88c9e5125a9d7f570d061df67a30b0981bc9a0/ssf/formulas.yaml#L154)

**Comment by myii** [comment]
@alias454 Anything else to do or is this ready for review and merging now?

**Comment by alias454** [comment]
@myii I'm not going to make any additional changes for the PR. Thanks for all of your help.

**Comment by aboe76** [comment]
@alias454 thanks for your hard work,

**Comment by myii** [comment]
@alias454 You're welcome.  With this work in place, it's an easy step to get `semantic-release` running.  I might do that in a short while.  Or did you still want to do that yourself?

Thanks for the merge, @aboe76.

**Pull request merged**
